### ISSUE TITLE
total_text and scut label

### ISSUE THREAD

**Issue by ChChwang** [MhLiao/MaskTextSpotter#23]
what do the labels of total_text and scut label look like?
The total_text‘s label is same to CTW1500?
and the scut using the char labels, whose each box has 8 value?

thanks a lot

**Comment by MhLiao** [comment]
@ChChwang We did not use CTW1500 in our paper since it is annotated in text lines instead of words. The SCUT dataset in our paper is another dataset that is proposed in "DeepText". We do not use the character annotations in the Total-Text dataset since the character-level annotations are not available when we prepared our ECCV paper. For a fair comparison, we also did not use them in the TPAMI version.

**Comment by ChChwang** [comment]
@MhLiao Do you means the words annotations of Total-Text were used in training in the TPAMI version?

**Comment by MhLiao** [comment]
@ChChwang Yes！
